using System.Globalization;
using System.Threading.RateLimiting;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using JiuManager.Configuracoes;
using JiuManager.Repositories;
using JiuManager.Services;
using JiuManager.Dados;
using JiuManager.Helpers;
var construtor = WebApplication.CreateBuilder(args);
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.GetCultureInfo("pt-BR");
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.GetCultureInfo("pt-BR");
construtor.Services.AddControllersWithViews(opcoes =>
{
    opcoes.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true;
    opcoes.ModelBindingMessageProvider.SetValueMustNotBeNullAccessor(_ => "Informe um valor válido.");
    opcoes.ModelBindingMessageProvider.SetAttemptedValueIsInvalidAccessor((valor, campo) => $"O valor informado para {campo} é inválido.");
    opcoes.ModelBindingMessageProvider.SetValueIsInvalidAccessor(_ => "O valor informado é inválido.");
    opcoes.ModelBindingMessageProvider.SetValueMustBeANumberAccessor(campo => $"Informe um número para {campo}.");
    opcoes.ModelBindingMessageProvider.SetMissingBindRequiredValueAccessor(campo => $"Informe {campo}.");
    opcoes.ModelBinderProviders.Insert(0, new JiuManager.Helpers.ProvedorDecimal());
    opcoes.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
    opcoes.Filters.Add<FiltroPermissao>();
});
construtor.Services.AddHttpContextAccessor();
construtor.Services.AddSingleton<CatalogoModulos>();
construtor.Services.AddSingleton<FabricaConexao>();
construtor.Services.AddScoped<ContextoEquipe>();
construtor.Services.AddScoped<ConsultaRepositorio>();
construtor.Services.AddScoped<TelaServico>();
construtor.Services.AddScoped<RelatorioServico>();
construtor.Services.AddScoped<RelatorioRepositorio>();
construtor.Services.AddScoped<PerfilAlunoRepositorio>();
construtor.Services.AddScoped<ImagemServico>();
construtor.Services.AddScoped<AutenticacaoRepositorio>();
construtor.Services.AddScoped<AutenticacaoServico>();
construtor.Services.AddScoped<PermissaoServico>();
construtor.Services.AddScoped<OperacaoRepositorio>();
construtor.Services.AddScoped<ChamadaServico>();
construtor.Services.AddScoped<DashboardServico>();
construtor.Services.AddScoped<DocumentoServico>();
construtor.Services.AddScoped<DocumentoRepositorio>();
construtor.Services.AddScoped<PermissaoRepositorio>();
construtor.Services.AdicionarModulos();
construtor.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(opcoes => { opcoes.LoginPath = "/Conta/Entrar"; opcoes.AccessDeniedPath = "/Conta/AcessoNegado"; opcoes.ExpireTimeSpan = TimeSpan.FromHours(8); opcoes.Cookie.Name = "JiuManager.Sessao"; opcoes.Cookie.HttpOnly = true; opcoes.Cookie.SameSite = SameSiteMode.Lax; opcoes.SlidingExpiration = true; opcoes.Events.OnValidatePrincipal = async contexto => { var repositorio = contexto.HttpContext.RequestServices.GetRequiredService<AutenticacaoRepositorio>(); var id = contexto.Principal?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value; var usuario = int.TryParse(id, out var numero) ? await repositorio.PorIdAsync(numero) : null; var selo = usuario == null ? "" : Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(usuario.SenhaHash))); if (usuario == null || contexto.Principal?.FindFirst("Sessao")?.Value != selo || contexto.Principal?.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value != usuario.Perfil || contexto.Principal?.FindFirst("EquipeId")?.Value != usuario.EquipeId.ToString()) contexto.RejectPrincipal(); }; });
construtor.Services.AddAuthorization();
construtor.Services.AddRateLimiter(opcoes => { opcoes.RejectionStatusCode = 429; opcoes.AddPolicy("login", contexto => RateLimitPartition.GetFixedWindowLimiter(contexto.Connection.RemoteIpAddress?.ToString() ?? "local", _ => new FixedWindowRateLimiterOptions { PermitLimit = 10, Window = TimeSpan.FromMinutes(1), QueueLimit = 0 })); });
var aplicacao = construtor.Build();
await InicializadorBanco.ExecutarAsync(aplicacao.Services, aplicacao.Configuration, aplicacao.Environment);
aplicacao.UseExceptionHandler("/Sistema/Erro");
if (!aplicacao.Environment.IsDevelopment()) aplicacao.UseHsts();
aplicacao.Use(async (contexto, proximo) => { contexto.Response.Headers["X-Content-Type-Options"] = "nosniff"; contexto.Response.Headers["X-Frame-Options"] = "SAMEORIGIN"; contexto.Response.Headers["Referrer-Policy"] = "strict-origin-when-cross-origin"; await proximo(); });
aplicacao.UseStaticFiles();
aplicacao.UseRouting();
aplicacao.UseRateLimiter();
aplicacao.UseAuthentication();
aplicacao.UseAuthorization();
aplicacao.MapControllerRoute(name: "padrao", pattern: "{controller=Dashboard}/{action=Index}/{id?}");
aplicacao.Run();
